### ISSUE TITLE
code TODOs

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-core#113]
There are a number of TODOs in the code and wanted to mention these specifically to make sure they are not forgotten. Specifically, the first affects the boardloader so I'd like to get the current thinking on it.

```
/trezor-core/embed/trezorhal/image.c, TODO: expiry mechanism needs to be ironed out before production or those devices won't accept expiring bootloaders (due to boardloader write protection).

/trezor-core/embed/trezorhal/image.h, TODO: change above limitation to 13 blocks after fixing writing to non-continuous area

/trezor-core/embed/bootloader/messages.c, TODO: pass info about installed firmware (vendor, version, etc.)

/trezor-core/embed/extmod/modtrezorconfig/norcow.c, TODO: error
```

**Comment by prusnak** [comment]
1) let's just keep it that way (boardloaders only accept bootloaders with no expiration set), for bootloader we can iron that out later, once we figure out how to securely get the timestamp into the device

2) good find! fixed in 936f0e3e268654550627fd7fe40ae4c1c3eec4ec

3) forgotten TODO, already done, removed in in 936f0e3e268654550627fd7fe40ae4c1c3eec4ec

4) fixed in 936f0e3e268654550627fd7fe40ae4c1c3eec4ec
