### ISSUE TITLE
Ethereum gas display problem when transferring tokens

### ISSUE THREAD

**Issue by ligi** [trezor/trezor-core#155]
When transferring tokens - transferring 1 WALL token in this test - the gas is displayed:
![20180308_232055](https://user-images.githubusercontent.com/111600/37179961-b54dd41c-2327-11e8-8aa9-6c737e7b0913.jpg)

* gas is not payed in the token but in ETH - soI think on the screen above there should be no mention of WALL

In this screen it is correct I guess - just the zeroes should be removed  and IMHO it should not be "wei WALL" what I think is behind there - just WALL. Seems a bit similar to #14 - just also happens when value is >1

![20180308_232012](https://user-images.githubusercontent.com/111600/37179951-b427f2d4-2327-11e8-9914-f54986bd99ff.jpg)

**Comment by prusnak** [comment]
Should be fixed in https://github.com/trezor/trezor-core/commit/8cdec0652e8da2d69cf16e5e7357e96048f09dcd


You can try building firmware using `build-docker.sh` - this will build unofficial build which will erase storage, careful!

Another option is to use emulator (`emu.sh`) but I am not sure how one can connect Android to the emulator (we emulate USB connection via UDP sockets).
