### ISSUE TITLE
U2F is incompatible between One and T

### ISSUE THREAD

**Issue by sammy007** [trezor/trezor-core#276]
> recovered my seed on model T (previously used in model One) and website refused to accept this U2F device "another device was used to register".

Confirmed

> It is supposed to work that way, but I think it is not thoroughly tested. I just tried it and I get the same problem.

For reference https://www.reddit.com/r/TREZOR/comments/8y2hbr/u2f_and_model_t/

**Comment by Perlover** [comment]
Confirm! Last current firmwares of Trezor One (1.6.2) & Trezor T (2.0.7) are incompatible for U2F (Chrome@LinuxMint, GMail tested)
But i found other problem too.

The Trezor One v1.6.2 works fine with GMail but v1.6.1 repeatly asks me "confirm" button again and again ("U2F Google..."). I thougth that there was bug and was fixed but i din't find some description about in changelog for 1.6.2

**Comment by Perlover** [comment]
As workaround i registered at services the Trezor T as second other hardware key and it works. So Trezor One and Trezor T from one seed work as different hardware keys. If you will make a new update to fix it some users can be affected (who activated first time the Trezor T not Trezor One)

**Comment by jhoenicke** [comment]
I looked over the code and found no obvious differences. But maybe some encoding issue.  The u2f key consists of 32 byte derivation path and 32 byte checksum.  The derivation path is used to get from the u2f master key to the private key and the checksum is a HMAC checksum over the private key, the app id and the derivation path.  If either the private key is different or the data that is check-summed this may explain why the key is rejected.

@Perlover the u2f counter is there to detect cloned devices, i.e., two devices with the same secret keys.  By allowing you to recover the secrets from the seed, we are moving outside the u2f specification and some websites are picky about the counter and will not allow you to log in with an old counter.  

When we added u2f, we discussed whether to make a device specific secret that can't be backed up, or make the secret derived from the seed.  We came to the conclusion that it is better to allow the user to make a clone in case the original Trezor broke. I see no big benefit of using a counter to disallow clones, as it usually locks the original owner out since the one who clones the device can just set a large enough counter.  We set the counter to a time-stamp on recovery to make sure it is increasing.  So usually the just recovered Trezor has a higher counter.

**Comment by jhoenicke** [comment]
I would like to get a unit test for this, but we first need to add a new UDP interface for u2f-hid.  There is currently no way to talk u2f to the emulator, right?

**Comment by jpochyla** [comment]
I've found the bug with @prusnak yesterday, it's a stupid endianity issue in keypath serialization, sorry :( It should be possible to fix it in a backwards-compatible manner.

@jhoenicke We were thinking about testing the `fido_u2f` app with a unit test, or adding another UDP port. Will discuss it with @prusnak today.

**Comment by prusnak** [comment]
We found the issue, here should have been `<L` for little-endian:

https://github.com/trezor/trezor-core/blob/master/src/apps/fido_u2f/__init__.py#L568
jpochyla is working on a fix already which should not brake things.

**Comment by prusnak** [comment]
Fixed via https://github.com/trezor/trezor-core/pull/288

**Comment by sammy007** [comment]
Is there a release scheduled with this fix?

**Comment by prusnak** [comment]
Yes, next release, planned in September will contain this.
