### ISSUE TITLE
Stellar: add signer operation

### ISSUE THREAD

**Issue by s-a-y** [trezor/trezor-core#463]
I'm using connect to sign transaction to add signer to the account
I was under impression, that public keys were replaced by strings for easy handling, but probably not everywhere, because operation
<img width="381" alt="screen shot 2019-01-16 at 3 35 31 pm" src="https://user-images.githubusercontent.com/1667781/51226657-7cc30f80-19a4-11e9-9605-1e234b9e69e8.png">
fails with following error
<img width="372" alt="screen shot 2019-01-16 at 3 36 41 pm" src="https://user-images.githubusercontent.com/1667781/51226668-89dffe80-19a4-11e9-9246-c755d02b9389.png">

So I tried to encode account as hex string
<img width="385" alt="screen shot 2019-01-16 at 3 41 21 pm" src="https://user-images.githubusercontent.com/1667781/51226802-391cd580-19a5-11e9-948a-5d85de63999b.png">

and it seems to be accepted, but there is a room for UI improvement
![photo_2019-01-16_15-42-12](https://user-images.githubusercontent.com/1667781/51226823-5a7dc180-19a5-11e9-94d3-8424c13c2283.jpg)

and I'm still getting invalid signature, not sure if that's related or a separate issue

**Comment by tsusanka** [comment]
If I've understood the [documentation](https://www.stellar.org/developers/guides/concepts/multi-sig.html#alternate-signature-types) correctly, it states that the additional signer can be either

1. public key 
1. pre-authorized transaction
1. hash

I believe this is the reason why the `signer_key` field is bytes and not string, because you can specify hash and not an address. The `signer_type` denotes what type it is.

----

The UI is definitely broken, I'll fix it. We should either a) convert the pubkey to an address and show it (probably preferred?) b) show the pubkey in hex.

----

However, this should not break the signature. Are you sure you're converting the address into a public key correctly? Using [our code](https://github.com/trezor/trezor-core/blob/master/src/apps/stellar/helpers.py#L21) I'm getting an address GBZBQ6.. from your public key `72187adb879c414346d77c71af8cce7b6eaa57b528e999fd91feae6b6418628e` (if I've copied it correctly).

**Comment by s-a-y** [comment]
Your explanation makes perfect sense, I guess I can make a simple utility library around trezor connect that would take Transaction from stellar-sdk and convert parameters to types required by trezor.

---

a) is definitely preferred, no user will be able to confirm if address is correct in hex.

---

I'm using 
```
import { StrKey} from 'stellar-sdk';
StrKey.decodeEd25519PublicKey(op.signer.ed25519PublicKey).toString('hex')
```

I wasn't sure, but now you've got the same representation as shown above on 3rd screenshot in my original post. 

I'll try to find time and make some sandbox in next couple of days, where we will be able to test submission to the network of signed transaction.

**Comment by s-a-y** [comment]
> Hmmm, I'm confused here a little bit, so it matches now?
I only state that my hex representation of the address matches the one you posted. But produced signature is still invalid

**Comment by tsusanka** [comment]
I think I got it, I'll push soon.
