### ISSUE TITLE
Flickering screen during PIN verification

### ISSUE THREAD

**Issue by 1000101** [trezor/trezor-core#495]
Screen is flickering while the progressbar circle is empty. After the first line of the circle is rendered, the flickering stops. It becomes clearly visible at 10th attempt

https://streamable.com/n7r1x

**Comment by prusnak** [comment]
The problem is here: https://github.com/trezor/trezor-core/blob/d86abc473f935a91ee7fd33411220bcdc2a19b6d/src/trezor/pin.py#L9

If `show_pin_timeout` is called with `progress == 0` the screen is cleared.

If timeout is bigger than 1000 seconds, `show_pin_timeout` is called with `progress == 0` multiple times, each time performing a clear screen.

**Comment by tsusanka** [comment]
Ping @jpochyla . Or have you discussed this in person?

**Comment by jpochyla** [comment]
Possible fix in 7533409

**Comment by prusnak** [comment]
Seems like a good fix!

Can we prepare a firmware with the commit and try entering PIN incorrectly 10 times?

**Comment by tsusanka** [comment]
LGTM. The screen does not flicker after 10th try. Branch master c55b6553.

Videos: https://streamable.com/6hy4v http://streamable.com/lwq0e
